version: "3.8"

services:
  scheduler-module:
    build:
      context: .
      dockerfile: Dockerfile
    image: gluesync-scheduler-module # molo17/gluesync-chronos if using MOLO17 Commercial License
    container_name: gluesync-scheduler-module
    network_mode: host
    volumes:
      - ./gs-license.dat:/opt/gluesync/data/gs-license.dat
      - ./security-config.json:/opt/gluesync/data/security-config.json
      - ./logs:/app/logs
    ports:
      - "1717:1717"
    command: uvicorn app:app --host 0.0.0.0 --port 1717
    environment:
      - CORE_HUB_URL=
      - ENTITY_START_TIMEOUT=2
      - HOST=0.0.0.0
      - PORT=1717
      - DEBUG=False
      - DB_URL=sqlite:///./scheduler.db
      - ALLOWED_ORIGINS=*
      - CRONTAB_USER=root
      - GLUESYNC_LICENSE_FILE=/opt/gluesync/data/gs-license.dat
      - GLUESYNC_USE_SSL=False
      - GLUESYNC_SECURITY_CONFIG=/opt/gluesync/data/security-config.json
